### ISSUE TITLE
Falling Fruit Alpha

### ISSUE THREAD

**Issue by Qrtn** [falling-fruit/falling-fruit-web#252]
## Description

Remaining tasks to complete for hand-off.

### P0

- [x] Hook up core forms @Qrtn 
  - [x] Add location: #148 
  - [x] Edit location: #149
  - [x] Add review
    - [x] Photo upload and ordering
  - [x] Edit review
  - [x] #250 
- [x] Fix core forms on mobile #264 @Qrtn 
- [x] Hook up auth forms @Qrtn 
  - [x] Sign-up
  - [x] Edit account
  - [x] #272 
  - [x] Email confirmation
  - [x] #250 
  - [x] #249 
- [x] #234 @Qrtn 
- [x] Mobile buttons/links to pages @SirajChokshi 
  - [x] Sign-up and log-in forms
  - [x] About pages
- [x] Review redesign: #161 @SirajChokshi 
  - [x] Logged-in user's reviews
  - [x] Star rating system/slider (also in forms)
- [x] Summary of reviews for a location @SirajChokshi 
- [x] Entry details polish @SirajChokshi 
  - [x] #238 
  - [x] #239 
  - [x] Incorporate `observed_on` date into review @SirajChokshi 
  - [x] Fix map mount by populating filter with no data initially
- [x] 404 redirects #45 @Qrtn 
- [x] #86 
- [x] In the Press page @SirajChokshi 
  - [x] Script to pull data from Google Sheet
  - [x] UI
- [x] Sharing the Harvest page
- [x] #333
- [x] Miscellaneous fixes
  - [x] Fix stepper appearance @SirajChokshi 
  - [x] Fix tags margin in entry details
  - [x] Fruiting summary decimal place
  - [x] Hitting back in mobile drawer should revert to overview first

**Comment by ezwelty** [comment]
@Qrtn @SirajChokshi Do you still feel that the remaining items under the `P0` header are worthy of `P0` priority? I labeled the two issues as `P1`, but that was partly because there wasn't enough information to judge the severity of the issue.

- [ ] Filter performance @SirajChokshi
  -  [ ] Investigate web worker 
- [ ] #192 @Qrtn 
- [ ] #224 @Qrtn
  - [ ] Fix current location on desktop Safari
  - [ ] Disable click when permission is denied (icon is X)

I would then suggest that you create new issues (or flesh out existing issues) as needed to cover these remaining items (including the one below, from the `P1` list), and that we close this issue, since the `P0`, `P1`, `P2` issue labels provide an overview of priority.

- [ ] Update rc-tree-select

**Comment by ezwelty** [comment]
Moved `P1`+ issues elsewhere (see below) and now closing this issue.

- https://github.com/falling-fruit/falling-fruit-web/issues/351
- https://github.com/falling-fruit/falling-fruit-web/issues/214

I can't reproduce location issues on Safari, so did not create an issue for this.
