### ISSUE TITLE
Improve geolocation and position tracking

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit-web#518]
When the track-position button is clicked, the device's current position is displayed on the map and the map updates to keep the current position at the center. If the map is panned, track-position is disabled and the current-position marker is removed from the map. In other words, it isn't possible to both see one's location and pan the map, which is an obvious limitation.

I propose that we:

- [ ] Display position (but stop centering on position) when map is panned. Track-position button remains active.
- [ ] Start centering on position if track-position button is clicked and active.
- [ ] Remove position and disable track-position button if track-position button is clicked while centering is active.

For the latter two, we could alternatively match the current mobile app behavior: it uses the track-position button for center-and-track / off, and adds a little blue dot to recenter-and-track after the map is panned:

<img src="https://github.com/user-attachments/assets/8adca510-8d01-4185-94f4-66b741707c3a" width="300px">

Perhaps this is more intuitive, but it requires an additional control.

The mobile app also shows position uncertainty and compass heading, and it is blue, which I think is more intuitive and familiar than the current orange. I think these would be improvements. See mobile app [logic](https://github.com/falling-fruit/falling-fruit-mobile/blob/b13144202ace75b41815424cdcfc8bed65b72989/src/coffee/search.coffee#L149) and [marker styling](https://github.com/falling-fruit/falling-fruit-mobile/blob/b13144202ace75b41815424cdcfc8bed65b72989/src/coffee/directives.coffee#L156).

**Comment by wbazant** [comment]
I was thinking about geolocation yesterday night, came back to this issue now, and I see we align on the centering being restrictive and annoying, and I think your proposal to add a state where a dot is visible but the map is no longer tracking the dot is a really useful idea. To start centering again, I propose the user should click twice - i.e. cycle through the "off" state - and maybe the "geolocating and not centering" should be slightly visually weaker from "geolocating and centering", e.g. a tiny bit more opaque or greyed out. 

I'll make this into an epic and merge the other issues into this one:

##  when map panning or place search should switch off geolocation tracking
#425
Given above, I think never - they should switch the centering off instead - and I'm now thinking if the dot is not visible on the map, we could instead display a pulsing triangle on the edge of the map, in the direction of the dot. The user can then switch off or re-center themselves.

## 'geolocation requested' on desktop can be stuck
#452 

On desktop, the proposed resolution is to make geolocation part of search: after pressing, do one request, populate the search box with the coordinates, and then display it like a coordinate search would get displayed, with a cross.

Devices in desktop layout don't change their position very much, so there's no need for re-centering or a pulsing dot. Additionally, the location is likely to be of limited correctness on desktop: my Chrome browser shows the location where I live, I think by using coordinates of my Android device, but my Firefox displays me somewhere in rural England.

## how much to pulse
#505

Proposed resolution is to limit the rate of pulsing to every five seconds, and try it in the field: see if my mobile Firefox starts to allow it and how the "Loading" starts to behave on my mobile Chrome.

**Comment by wbazant** [comment]
Proposed resolution:
- throttle to use geolocation every five seconds
- do not switch off geolocation when panning the map
- when map is panned by more than a meter, stop tracking/centering but still display the dot
- when displaying the dot but not tracking/centering, animate the dot less, allow clicking on it, and add opacity to the button
- clicking on the "displaying but not centering" dot re-centers and starts tracking
- add a sixty second timeout to geolocation data
- keep track of when the map is panned, and don't issue centering commands while the user is panning
